Repository brazil-data-cube/bdc-core, pull requests merged in 2019-10, with the labels that each got.

#16 decorator to auth_required
  bdc_core/decorators/auth.py
  requirements.txt
Labels: enhancement

#17 fix validate scope - decorator oauth
  bdc_core/decorators/auth.py
Labels: bug

#18 fix setup dependencies
  requirements.txt
  setup.py
Labels: bug, enhancement

#19 Fix setup jsonschema version and docs import
  docker/Dockerfile
  docs/source/conf.py
  setup.py
Labels: bug
