Repository brazil-data-cube/bdc-core, pull requests merged in 2019-07, with the labels that each got.

#1 Add decorator 'require_model' to validate flask requests with JSON Schema
  README.md
  bdc_core/__init__.py
  bdc_core/decorators/__init__.py
  bdc_core/decorators/validators.py
  requirements.txt
  setup.py
  tests/bdc_core/test_decorators.py
Labels: documentation, enhancement

#3 Fix find_package on setup.py
  setup.py
Labels: bug

#4 Add init py in utils package
  bdc_core/utils/__init__.py
  setup.py
Labels: bug

#6 Improve APIResource exception handler
  bdc_core/utils/flask.py
  tests/bdc_core/test_decorators.py
  tests/bdc_core/utils/test_flask.py
Labels: enhancement

#10 Add readthedocs support
  .gitignore
  bdc_core/decorators/__init__.py
  bdc_core/decorators/validators.py
  docs/Makefile
  docs/make.bat
  docs/source/api.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  requirements.txt
Labels: documentation, enhancement

#12 Add integration with Jenkins
  .pylintrc
  Jenkinsfile
  bdc_core/decorators/validators.py
  bdc_core/utils/flask.py
  bdc_core/utils/python.py
  requirements.txt
Labels: enhancement

#13 Improve tests - exception on invalid schema
  tests/bdc_core/test_decorators.py
Labels: enhancement
